CREATE TABLE RECON_AUDIT (
    JOB_ID NUMBER,
    JOB_NAME VARCHAR2(255),
    EXECUTION_TIMESTAMP TIMESTAMP,
    AUDIT_TYPE VARCHAR2(50), -- 'SUMMARY' or 'MISMATCH'
    STATUS VARCHAR2(50),

    -- Summary Fields
    SOURCE_COUNT NUMBER,
    TARGET_COUNT NUMBER,
    COUNT_MATCH CHAR(1),

    -- Mismatch Fields
    MISMATCH_TYPE VARCHAR2(255),
    PRIMARY_KEY VARCHAR2(1000),
    MISMATCHED_COLUMN VARCHAR2(255),
    SOURCE_VALUE VARCHAR2(4000),
    TARGET_VALUE VARCHAR2(4000)
);
