CREATE TABLE MISMATCH_DETAILS (
    JOB_ID NUMBER,
    EXECUTION_TIMESTAMP TIMESTAMP,
    MISMATCH_TYPE VARCHAR2(255),
    PRIMARY_KEY VARCHAR2(1000),
    MISMATCHED_COLUMN VARCHAR2(255),
    SOURCE_VALUE VARCHAR2(4000),
    TARGET_VALUE VARCHAR2(4000)
);
