CREATE TABLE RECON_CONFIG (
    JOB_ID NUMBER PRIMARY KEY,
    JOB_NAME VARCHAR2(255) UNIQUE NOT NULL,
    RECON_MODE VARCHAR2(20) NOT NULL, -- 'SOURCE_TO_TARGET' or 'SOURCE_TO_SQL'

    -- Source Details
    SOURCE_TYPE VARCHAR2(20) NOT NULL, -- 'CSV', 'EXCEL', 'TEXT', 'DAT', 'PARQUET', 'ORC', 'HIVE', 'JDBC'
    SOURCE_PATH VARCHAR2(1000),
    SOURCE_JDBC_URL VARCHAR2(1000),
    SOURCE_JDBC_USER VARCHAR2(255),
    SOURCE_JDBC_PASSWORD VARCHAR2(255),
    SOURCE_JDBC_DRIVER VARCHAR2(255),
    SOURCE_HIVE_TABLE VARCHAR2(255),
    SOURCE_PRIMARY_KEYS VARCHAR2(1000),

    -- Target Details (for SOURCE_TO_TARGET mode)
    TARGET_TYPE VARCHAR2(20), -- 'HIVE', 'PARQUET', 'ORC'
    TARGET_PATH VARCHAR2(1000),
    TARGET_HIVE_TABLE VARCHAR2(255),
    TARGET_PRIMARY_KEYS VARCHAR2(1000),

    -- SQL Details (for SOURCE_TO_SQL mode)
    RECON_SQL CLOB,

    -- Reconciliation Types (Flags: 'Y'/'N')
    DO_COLUMN_COMPARISON CHAR(1) DEFAULT 'N',
    DO_BUSINESS_RULE_VALIDATION CHAR(1) DEFAULT 'N',
    DO_COUNT_RECONCILIATION CHAR(1) DEFAULT 'N',
    DO_EXTRA_MISSING_CHECK CHAR(1) DEFAULT 'N',
    DO_THRESHOLD_VALIDATION CHAR(1) DEFAULT 'N',
    DO_SCHEMA_DRIFT_DETECTION CHAR(1) DEFAULT 'N',

    -- Mappings and Thresholds
    COLUMN_MAPPINGS CLOB, -- 'source_col1:target_col1,source_col2:target_col2'
    THRESHOLD_SETTINGS CLOB, -- 'col1:absolute:100,col2:percentage:5.5'

    -- Email Settings
    EMAIL_RECIPIENTS VARCHAR2(1000),
    EMAIL_SUBJECT VARCHAR2(255),

    -- Auditing
    AUDIT_HIVE_TABLE VARCHAR2(255),
    MISMATCH_HIVE_TABLE VARCHAR2(255),

    -- Job Control
    IS_ACTIVE CHAR(1) DEFAULT 'Y'
);
